name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  key: # change this
    required: true
    description: 'key'
outputs:
  value:
    description: the output
runs:
  using: 'node12'
  main: 'dist/index.js'
